version: '3.7'
services:
    php:
      build:
            context: .
            dockerfile: Dockerfile
      container_name: labo3
      ports:
            - 9988:8000
      volumes:
        - ./back:/var/www/html/
    mysql:
            image: mysql:5.7
            container_name: mysql
            environment:
                MYSQL_DATABASE: lol
                MYSQL_USER: lol
                MYSQL_PASSWORD: noquiero
                MYSQL_ROOT_PASSWORD: admin
            ports:
                - 6933:3306
            volumes:
                - datoslabo:/var/lib/mysql
            depends_on:
                - php
    phpMyAdmin:
        image: phpmyadmin:latest
        container_name: phpMyAdmin
        environment:
            MYSQL_ROOT_PASSWORD: admin
            PMA_HOST: mysql
        depends_on:
            - mysql
        ports:
            - 9090:80
volumes: 
    .:
    datoslabo:
