#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#api_login_check:
 #   path: /api/login_check
register:
    path: /api/register
    controller: App\Controller\AuthController::registrar
    methods: POST
api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser
test:
    path: /api/test
    controller: App\Controller\ApiController::test