<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ZzNagQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ZzNagQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0ZzNagQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0ZzNagQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0ZzNagQ\App_KernelDevDebugContainer([
    'container.build_hash' => '0ZzNagQ',
    'container.build_id' => '13a0d50a',
    'container.build_time' => 1639770456,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ZzNagQ');
