<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzqtmxL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzqtmxL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzqtmxL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzqtmxL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzqtmxL\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzqtmxL',
    'container.build_id' => 'd5d8b5ee',
    'container.build_time' => 1639765594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzqtmxL');
